---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natsstreamingclusters.streaming.nats.io
spec:
  group: streaming.nats.io
  names:
    kind: NatsStreamingCluster
    listKind: NatsStreamingClusterList
    plural: natsstreamingclusters
    singular: natsstreamingcluster
    shortNames: ["stanclusters", "stancluster"]
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nats-streaming-operator
  namespace: nats-io
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-streaming-operator
  template:
    metadata:
      labels:
        name: nats-streaming-operator
    spec:
      serviceAccountName: nats-streaming-operator
      containers:
      - name: nats-streaming-operator
        image: wallyqs/nats-streaming-operator:dev
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
